from __future__ import annotations

import csv
from pathlib import Path

STRING_DTYPE = "string[python]"
OUTPUT_PATHS = (
    Path("data/processed/lumen_cells.csv"),
    Path("scripts/data/processed/lumen_cells.csv"),
)
COLUMN_DTYPES = {
    "cell_id": STRING_DTYPE,
    "lat": "float64",
    "lon": "float64",
    "state_code": STRING_DTYPE,
    "state_name": STRING_DTYPE,
    "electricity_maps_zone_id": STRING_DTYPE,
    "month": STRING_DTYPE,
    "solar_cf": "float64",
    "wind_cf": "float64",
    "avg_electricity_cost_cents_per_kwh": "float64",
    "pct_solar_state": "float64",
    "pct_wind_state": "float64",
    "pct_hydro_state": "float64",
    "pct_fossil_state": "float64",
    "carbon_g_per_kwh_zone": "float64",
    "renewable_pct_zone": "float64",
    "carbon_free_pct_zone": "float64",
}

ROWS: list[dict[str, str | float]] = [
    {
        "cell_id": "pnw_001",
        "lat": 47.6062,
        "lon": -122.3321,
        "state_code": "WA",
        "state_name": "Washington",
        "electricity_maps_zone_id": "US-NW-BPAT",
        "month": "2026-02",
        "solar_cf": 0.18,
        "wind_cf": 0.35,
        "avg_electricity_cost_cents_per_kwh": 4.2,
        "pct_solar_state": 4.0,
        "pct_wind_state": 8.0,
        "pct_hydro_state": 66.0,
        "pct_fossil_state": 18.0,
        "carbon_g_per_kwh_zone": 120.0,
        "renewable_pct_zone": 82.0,
        "carbon_free_pct_zone": 89.0,
    },
    {
        "cell_id": "pnw_002",
        "lat": 45.5152,
        "lon": -122.6784,
        "state_code": "OR",
        "state_name": "Oregon",
        "electricity_maps_zone_id": "US-NW-BPAT",
        "month": "2026-02",
        "solar_cf": 0.19,
        "wind_cf": 0.33,
        "avg_electricity_cost_cents_per_kwh": 3.9,
        "pct_solar_state": 3.0,
        "pct_wind_state": 12.0,
        "pct_hydro_state": 52.0,
        "pct_fossil_state": 19.0,
        "carbon_g_per_kwh_zone": 110.0,
        "renewable_pct_zone": 76.0,
        "carbon_free_pct_zone": 84.0,
    },
    {
        "cell_id": "ca_001",
        "lat": 36.7783,
        "lon": -119.4179,
        "state_code": "CA",
        "state_name": "California",
        "electricity_maps_zone_id": "US-CAL-CISO",
        "month": "2026-02",
        "solar_cf": 0.28,
        "wind_cf": 0.22,
        "avg_electricity_cost_cents_per_kwh": 6.1,
        "pct_solar_state": 28.0,
        "pct_wind_state": 7.0,
        "pct_hydro_state": 10.0,
        "pct_fossil_state": 33.0,
        "carbon_g_per_kwh_zone": 180.0,
        "renewable_pct_zone": 54.0,
        "carbon_free_pct_zone": 63.0,
    },
    {
        "cell_id": "ca_002",
        "lat": 34.0522,
        "lon": -118.2437,
        "state_code": "CA",
        "state_name": "California",
        "electricity_maps_zone_id": "US-CAL-CISO",
        "month": "2026-02",
        "solar_cf": 0.27,
        "wind_cf": 0.20,
        "avg_electricity_cost_cents_per_kwh": 6.6,
        "pct_solar_state": 28.0,
        "pct_wind_state": 7.0,
        "pct_hydro_state": 10.0,
        "pct_fossil_state": 33.0,
        "carbon_g_per_kwh_zone": 190.0,
        "renewable_pct_zone": 54.0,
        "carbon_free_pct_zone": 63.0,
    },
    {
        "cell_id": "desert_001",
        "lat": 32.2226,
        "lon": -110.9747,
        "state_code": "AZ",
        "state_name": "Arizona",
        "electricity_maps_zone_id": "US-SW-AZPS",
        "month": "2026-02",
        "solar_cf": 0.32,
        "wind_cf": 0.17,
        "avg_electricity_cost_cents_per_kwh": 4.6,
        "pct_solar_state": 8.0,
        "pct_wind_state": 7.0,
        "pct_hydro_state": 5.0,
        "pct_fossil_state": 46.0,
        "carbon_g_per_kwh_zone": 250.0,
        "renewable_pct_zone": 31.0,
        "carbon_free_pct_zone": 44.0,
    },
    {
        "cell_id": "desert_002",
        "lat": 33.4484,
        "lon": -112.0740,
        "state_code": "AZ",
        "state_name": "Arizona",
        "electricity_maps_zone_id": "US-SW-AZPS",
        "month": "2026-02",
        "solar_cf": 0.31,
        "wind_cf": 0.18,
        "avg_electricity_cost_cents_per_kwh": 4.8,
        "pct_solar_state": 8.0,
        "pct_wind_state": 7.0,
        "pct_hydro_state": 5.0,
        "pct_fossil_state": 46.0,
        "carbon_g_per_kwh_zone": 280.0,
        "renewable_pct_zone": 31.0,
        "carbon_free_pct_zone": 44.0,
    },
    {
        "cell_id": "rockies_001",
        "lat": 39.7392,
        "lon": -104.9903,
        "state_code": "CO",
        "state_name": "Colorado",
        "electricity_maps_zone_id": "US-CENT-PSCO",
        "month": "2026-02",
        "solar_cf": 0.26,
        "wind_cf": 0.31,
        "avg_electricity_cost_cents_per_kwh": 4.1,
        "pct_solar_state": 7.0,
        "pct_wind_state": 24.0,
        "pct_hydro_state": 4.0,
        "pct_fossil_state": 47.0,
        "carbon_g_per_kwh_zone": 430.0,
        "renewable_pct_zone": 35.0,
        "carbon_free_pct_zone": 46.0,
    },
    {
        "cell_id": "rockies_002",
        "lat": 41.1400,
        "lon": -104.8202,
        "state_code": "WY",
        "state_name": "Wyoming",
        "electricity_maps_zone_id": "US-WEST-PACE",
        "month": "2026-02",
        "solar_cf": 0.25,
        "wind_cf": 0.38,
        "avg_electricity_cost_cents_per_kwh": 3.8,
        "pct_solar_state": 1.0,
        "pct_wind_state": 15.0,
        "pct_hydro_state": 2.0,
        "pct_fossil_state": 79.0,
        "carbon_g_per_kwh_zone": 410.0,
        "renewable_pct_zone": 18.0,
        "carbon_free_pct_zone": 20.0,
    },
    {
        "cell_id": "plains_001",
        "lat": 39.0119,
        "lon": -98.4842,
        "state_code": "KS",
        "state_name": "Kansas",
        "electricity_maps_zone_id": "US-CENT-SWPP",
        "month": "2026-02",
        "solar_cf": 0.24,
        "wind_cf": 0.43,
        "avg_electricity_cost_cents_per_kwh": 3.6,
        "pct_solar_state": 1.0,
        "pct_wind_state": 45.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 21.0,
        "carbon_g_per_kwh_zone": 500.0,
        "renewable_pct_zone": 47.0,
        "carbon_free_pct_zone": 48.0,
    },
    {
        "cell_id": "plains_002",
        "lat": 35.4676,
        "lon": -97.5164,
        "state_code": "OK",
        "state_name": "Oklahoma",
        "electricity_maps_zone_id": "US-CENT-SWPP",
        "month": "2026-02",
        "solar_cf": 0.25,
        "wind_cf": 0.40,
        "avg_electricity_cost_cents_per_kwh": 3.7,
        "pct_solar_state": 1.0,
        "pct_wind_state": 42.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 33.0,
        "carbon_g_per_kwh_zone": 470.0,
        "renewable_pct_zone": 44.0,
        "carbon_free_pct_zone": 45.0,
    },
    {
        "cell_id": "plains_003",
        "lat": 46.8772,
        "lon": -96.7898,
        "state_code": "ND",
        "state_name": "North Dakota",
        "electricity_maps_zone_id": "US-MIDW-MISO",
        "month": "2026-02",
        "solar_cf": 0.21,
        "wind_cf": 0.41,
        "avg_electricity_cost_cents_per_kwh": 3.5,
        "pct_solar_state": 1.0,
        "pct_wind_state": 36.0,
        "pct_hydro_state": 3.0,
        "pct_fossil_state": 41.0,
        "carbon_g_per_kwh_zone": 455.0,
        "renewable_pct_zone": 40.0,
        "carbon_free_pct_zone": 52.0,
    },
    {
        "cell_id": "tx_001",
        "lat": 31.9686,
        "lon": -99.9018,
        "state_code": "TX",
        "state_name": "Texas",
        "electricity_maps_zone_id": "US-TEX-ERCO",
        "month": "2026-02",
        "solar_cf": 0.27,
        "wind_cf": 0.39,
        "avg_electricity_cost_cents_per_kwh": 3.4,
        "pct_solar_state": 5.0,
        "pct_wind_state": 28.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 56.0,
        "carbon_g_per_kwh_zone": 390.0,
        "renewable_pct_zone": 34.0,
        "carbon_free_pct_zone": 39.0,
    },
    {
        "cell_id": "tx_002",
        "lat": 29.4241,
        "lon": -98.4936,
        "state_code": "TX",
        "state_name": "Texas",
        "electricity_maps_zone_id": "US-TEX-ERCO",
        "month": "2026-02",
        "solar_cf": 0.26,
        "wind_cf": 0.29,
        "avg_electricity_cost_cents_per_kwh": 3.5,
        "pct_solar_state": 5.0,
        "pct_wind_state": 28.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 56.0,
        "carbon_g_per_kwh_zone": 360.0,
        "renewable_pct_zone": 34.0,
        "carbon_free_pct_zone": 39.0,
    },
    {
        "cell_id": "tx_003",
        "lat": 33.5779,
        "lon": -101.8552,
        "state_code": "TX",
        "state_name": "Texas",
        "electricity_maps_zone_id": "US-TEX-ERCO",
        "month": "2026-02",
        "solar_cf": 0.29,
        "wind_cf": 0.36,
        "avg_electricity_cost_cents_per_kwh": 3.3,
        "pct_solar_state": 5.0,
        "pct_wind_state": 28.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 56.0,
        "carbon_g_per_kwh_zone": 345.0,
        "renewable_pct_zone": 34.0,
        "carbon_free_pct_zone": 39.0,
    },
    {
        "cell_id": "midwest_001",
        "lat": 41.8781,
        "lon": -87.6298,
        "state_code": "IL",
        "state_name": "Illinois",
        "electricity_maps_zone_id": "US-MIDW-MISO",
        "month": "2026-02",
        "solar_cf": 0.20,
        "wind_cf": 0.32,
        "avg_electricity_cost_cents_per_kwh": 4.6,
        "pct_solar_state": 1.0,
        "pct_wind_state": 12.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 20.0,
        "carbon_g_per_kwh_zone": 320.0,
        "renewable_pct_zone": 15.0,
        "carbon_free_pct_zone": 74.0,
    },
    {
        "cell_id": "midwest_002",
        "lat": 44.9778,
        "lon": -93.2650,
        "state_code": "MN",
        "state_name": "Minnesota",
        "electricity_maps_zone_id": "US-MIDW-MISO",
        "month": "2026-02",
        "solar_cf": 0.19,
        "wind_cf": 0.34,
        "avg_electricity_cost_cents_per_kwh": 4.3,
        "pct_solar_state": 2.0,
        "pct_wind_state": 25.0,
        "pct_hydro_state": 3.0,
        "pct_fossil_state": 28.0,
        "carbon_g_per_kwh_zone": 290.0,
        "renewable_pct_zone": 31.0,
        "carbon_free_pct_zone": 56.0,
    },
    {
        "cell_id": "midwest_003",
        "lat": 39.7684,
        "lon": -86.1581,
        "state_code": "IN",
        "state_name": "Indiana",
        "electricity_maps_zone_id": "US-MIDW-MISO",
        "month": "2026-02",
        "solar_cf": 0.21,
        "wind_cf": 0.28,
        "avg_electricity_cost_cents_per_kwh": 4.4,
        "pct_solar_state": 1.0,
        "pct_wind_state": 9.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 67.0,
        "carbon_g_per_kwh_zone": 490.0,
        "renewable_pct_zone": 12.0,
        "carbon_free_pct_zone": 12.0,
    },
    {
        "cell_id": "gulf_001",
        "lat": 29.7604,
        "lon": -95.3698,
        "state_code": "TX",
        "state_name": "Texas",
        "electricity_maps_zone_id": "US-TEX-ERCO",
        "month": "2026-02",
        "solar_cf": 0.24,
        "wind_cf": 0.28,
        "avg_electricity_cost_cents_per_kwh": 3.8,
        "pct_solar_state": 5.0,
        "pct_wind_state": 28.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 56.0,
        "carbon_g_per_kwh_zone": 350.0,
        "renewable_pct_zone": 34.0,
        "carbon_free_pct_zone": 39.0,
    },
    {
        "cell_id": "gulf_002",
        "lat": 30.4515,
        "lon": -91.1871,
        "state_code": "LA",
        "state_name": "Louisiana",
        "electricity_maps_zone_id": "US-MIDW-MISO",
        "month": "2026-02",
        "solar_cf": 0.23,
        "wind_cf": 0.25,
        "avg_electricity_cost_cents_per_kwh": 4.0,
        "pct_solar_state": 1.0,
        "pct_wind_state": 1.0,
        "pct_hydro_state": 0.0,
        "pct_fossil_state": 74.0,
        "carbon_g_per_kwh_zone": 370.0,
        "renewable_pct_zone": 5.0,
        "carbon_free_pct_zone": 25.0,
    },
    {
        "cell_id": "gulf_003",
        "lat": 30.3322,
        "lon": -81.6557,
        "state_code": "FL",
        "state_name": "Florida",
        "electricity_maps_zone_id": "US-FLA-FMPP",
        "month": "2026-02",
        "solar_cf": 0.22,
        "wind_cf": 0.20,
        "avg_electricity_cost_cents_per_kwh": 4.5,
        "pct_solar_state": 6.0,
        "pct_wind_state": 0.0,
        "pct_hydro_state": 0.0,
        "pct_fossil_state": 74.0,
        "carbon_g_per_kwh_zone": 310.0,
        "renewable_pct_zone": 9.0,
        "carbon_free_pct_zone": 31.0,
    },
    {
        "cell_id": "southeast_001",
        "lat": 33.7490,
        "lon": -84.3880,
        "state_code": "GA",
        "state_name": "Georgia",
        "electricity_maps_zone_id": "US-SE-SOCO",
        "month": "2026-02",
        "solar_cf": 0.23,
        "wind_cf": 0.21,
        "avg_electricity_cost_cents_per_kwh": 4.9,
        "pct_solar_state": 3.0,
        "pct_wind_state": 0.0,
        "pct_hydro_state": 4.0,
        "pct_fossil_state": 39.0,
        "carbon_g_per_kwh_zone": 340.0,
        "renewable_pct_zone": 7.0,
        "carbon_free_pct_zone": 44.0,
    },
    {
        "cell_id": "southeast_002",
        "lat": 35.2271,
        "lon": -80.8431,
        "state_code": "NC",
        "state_name": "North Carolina",
        "electricity_maps_zone_id": "US-SE-DUK",
        "month": "2026-02",
        "solar_cf": 0.22,
        "wind_cf": 0.19,
        "avg_electricity_cost_cents_per_kwh": 4.7,
        "pct_solar_state": 6.0,
        "pct_wind_state": 0.0,
        "pct_hydro_state": 2.0,
        "pct_fossil_state": 41.0,
        "carbon_g_per_kwh_zone": 320.0,
        "renewable_pct_zone": 9.0,
        "carbon_free_pct_zone": 51.0,
    },
    {
        "cell_id": "southeast_003",
        "lat": 36.1627,
        "lon": -86.7816,
        "state_code": "TN",
        "state_name": "Tennessee",
        "electricity_maps_zone_id": "US-TVA-TVA",
        "month": "2026-02",
        "solar_cf": 0.21,
        "wind_cf": 0.20,
        "avg_electricity_cost_cents_per_kwh": 4.3,
        "pct_solar_state": 1.0,
        "pct_wind_state": 0.0,
        "pct_hydro_state": 10.0,
        "pct_fossil_state": 22.0,
        "carbon_g_per_kwh_zone": 410.0,
        "renewable_pct_zone": 12.0,
        "carbon_free_pct_zone": 54.0,
    },
    {
        "cell_id": "northeast_001",
        "lat": 42.3601,
        "lon": -71.0589,
        "state_code": "MA",
        "state_name": "Massachusetts",
        "electricity_maps_zone_id": "US-NE-ISNE",
        "month": "2026-02",
        "solar_cf": 0.17,
        "wind_cf": 0.24,
        "avg_electricity_cost_cents_per_kwh": 7.1,
        "pct_solar_state": 3.0,
        "pct_wind_state": 4.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 57.0,
        "carbon_g_per_kwh_zone": 240.0,
        "renewable_pct_zone": 18.0,
        "carbon_free_pct_zone": 32.0,
    },
    {
        "cell_id": "northeast_002",
        "lat": 40.7128,
        "lon": -74.0060,
        "state_code": "NY",
        "state_name": "New York",
        "electricity_maps_zone_id": "US-NY-NYIS",
        "month": "2026-02",
        "solar_cf": 0.16,
        "wind_cf": 0.20,
        "avg_electricity_cost_cents_per_kwh": 7.6,
        "pct_solar_state": 2.0,
        "pct_wind_state": 5.0,
        "pct_hydro_state": 22.0,
        "pct_fossil_state": 32.0,
        "carbon_g_per_kwh_zone": 260.0,
        "renewable_pct_zone": 29.0,
        "carbon_free_pct_zone": 62.0,
    },
    {
        "cell_id": "northeast_003",
        "lat": 39.9526,
        "lon": -75.1652,
        "state_code": "PA",
        "state_name": "Pennsylvania",
        "electricity_maps_zone_id": "US-MIDA-PJM",
        "month": "2026-02",
        "solar_cf": 0.18,
        "wind_cf": 0.21,
        "avg_electricity_cost_cents_per_kwh": 6.3,
        "pct_solar_state": 1.0,
        "pct_wind_state": 2.0,
        "pct_hydro_state": 1.0,
        "pct_fossil_state": 39.0,
        "carbon_g_per_kwh_zone": 300.0,
        "renewable_pct_zone": 4.0,
        "carbon_free_pct_zone": 40.0,
    },
    {
        "cell_id": "appalachia_001",
        "lat": 38.3498,
        "lon": -81.6326,
        "state_code": "WV",
        "state_name": "West Virginia",
        "electricity_maps_zone_id": "US-MIDA-PJM",
        "month": "2026-02",
        "solar_cf": 0.19,
        "wind_cf": 0.23,
        "avg_electricity_cost_cents_per_kwh": 4.5,
        "pct_solar_state": 0.0,
        "pct_wind_state": 3.0,
        "pct_hydro_state": 2.0,
        "pct_fossil_state": 89.0,
        "carbon_g_per_kwh_zone": 610.0,
        "renewable_pct_zone": 5.0,
        "carbon_free_pct_zone": 5.0,
    },
    {
        "cell_id": "appalachia_002",
        "lat": 37.5407,
        "lon": -77.4360,
        "state_code": "VA",
        "state_name": "Virginia",
        "electricity_maps_zone_id": "US-MIDA-PJM",
        "month": "2026-02",
        "solar_cf": 0.20,
        "wind_cf": 0.22,
        "avg_electricity_cost_cents_per_kwh": 5.0,
        "pct_solar_state": 2.0,
        "pct_wind_state": 0.0,
        "pct_hydro_state": 3.0,
        "pct_fossil_state": 48.0,
        "carbon_g_per_kwh_zone": 400.0,
        "renewable_pct_zone": 5.0,
        "carbon_free_pct_zone": 42.0,
    },
]


def build_fixture_rows() -> list[dict[str, str | float]]:
    return [{column: row[column] for column in COLUMN_DTYPES} for row in ROWS]


def main() -> None:
    rows = build_fixture_rows()
    for output_path in OUTPUT_PATHS:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(COLUMN_DTYPES))
            writer.writeheader()
            writer.writerows(rows)
        print(f"Wrote {len(rows)} rows to {output_path}")


if __name__ == "__main__":
    main()
