from __future__ import annotations

from pathlib import Path

import pandas as pd

OUTPUT_PATH = Path("data/processed/lumen_cells.parquet")
STRING_DTYPE = "string[python]"
COLUMN_DTYPES = {
    "cell_id": STRING_DTYPE,
    "lat": "float64",
    "lon": "float64",
    "region": STRING_DTYPE,
    "solar_cf": "float64",
    "wind_cf": "float64",
    "avg_price_per_mwh": "float64",
    "carbon_intensity_g_per_kwh": "float64",
    "nearest_transmission_km": "float64",
}

ROWS: list[dict[str, str | float]] = [
    {
        "cell_id": "pnw_001",
        "lat": 47.6062,
        "lon": -122.3321,
        "region": "Pacific Northwest",
        "solar_cf": 0.18,
        "wind_cf": 0.35,
        "avg_price_per_mwh": 42.0,
        "carbon_intensity_g_per_kwh": 120.0,
        "nearest_transmission_km": 6.2,
    },
    {
        "cell_id": "pnw_002",
        "lat": 45.5152,
        "lon": -122.6784,
        "region": "Pacific Northwest",
        "solar_cf": 0.19,
        "wind_cf": 0.33,
        "avg_price_per_mwh": 39.0,
        "carbon_intensity_g_per_kwh": 110.0,
        "nearest_transmission_km": 8.4,
    },
    {
        "cell_id": "ca_001",
        "lat": 36.7783,
        "lon": -119.4179,
        "region": "California",
        "solar_cf": 0.28,
        "wind_cf": 0.22,
        "avg_price_per_mwh": 61.0,
        "carbon_intensity_g_per_kwh": 180.0,
        "nearest_transmission_km": 5.1,
    },
    {
        "cell_id": "ca_002",
        "lat": 34.0522,
        "lon": -118.2437,
        "region": "California",
        "solar_cf": 0.27,
        "wind_cf": 0.2,
        "avg_price_per_mwh": 66.0,
        "carbon_intensity_g_per_kwh": 190.0,
        "nearest_transmission_km": 12.7,
    },
    {
        "cell_id": "desert_001",
        "lat": 32.2226,
        "lon": -110.9747,
        "region": "Desert Southwest",
        "solar_cf": 0.32,
        "wind_cf": 0.17,
        "avg_price_per_mwh": 46.0,
        "carbon_intensity_g_per_kwh": 250.0,
        "nearest_transmission_km": 5.5,
    },
    {
        "cell_id": "desert_002",
        "lat": 33.4484,
        "lon": -112.074,
        "region": "Desert Southwest",
        "solar_cf": 0.31,
        "wind_cf": 0.18,
        "avg_price_per_mwh": 48.0,
        "carbon_intensity_g_per_kwh": 280.0,
        "nearest_transmission_km": 9.5,
    },
    {
        "cell_id": "rockies_001",
        "lat": 39.7392,
        "lon": -104.9903,
        "region": "Rockies",
        "solar_cf": 0.26,
        "wind_cf": 0.31,
        "avg_price_per_mwh": 41.0,
        "carbon_intensity_g_per_kwh": 430.0,
        "nearest_transmission_km": 10.2,
    },
    {
        "cell_id": "rockies_002",
        "lat": 41.1400,
        "lon": -104.8202,
        "region": "Rockies",
        "solar_cf": 0.25,
        "wind_cf": 0.38,
        "avg_price_per_mwh": 38.0,
        "carbon_intensity_g_per_kwh": 410.0,
        "nearest_transmission_km": 6.8,
    },
    {
        "cell_id": "plains_001",
        "lat": 39.0119,
        "lon": -98.4842,
        "region": "Great Plains",
        "solar_cf": 0.24,
        "wind_cf": 0.43,
        "avg_price_per_mwh": 36.0,
        "carbon_intensity_g_per_kwh": 500.0,
        "nearest_transmission_km": 4.3,
    },
    {
        "cell_id": "plains_002",
        "lat": 35.4676,
        "lon": -97.5164,
        "region": "Great Plains",
        "solar_cf": 0.25,
        "wind_cf": 0.4,
        "avg_price_per_mwh": 37.0,
        "carbon_intensity_g_per_kwh": 470.0,
        "nearest_transmission_km": 5.9,
    },
    {
        "cell_id": "plains_003",
        "lat": 46.8772,
        "lon": -96.7898,
        "region": "Great Plains",
        "solar_cf": 0.21,
        "wind_cf": 0.41,
        "avg_price_per_mwh": 35.0,
        "carbon_intensity_g_per_kwh": 455.0,
        "nearest_transmission_km": 7.1,
    },
    {
        "cell_id": "tx_001",
        "lat": 31.9686,
        "lon": -99.9018,
        "region": "Texas",
        "solar_cf": 0.27,
        "wind_cf": 0.39,
        "avg_price_per_mwh": 34.0,
        "carbon_intensity_g_per_kwh": 390.0,
        "nearest_transmission_km": 3.8,
    },
    {
        "cell_id": "tx_002",
        "lat": 29.4241,
        "lon": -98.4936,
        "region": "Texas",
        "solar_cf": 0.26,
        "wind_cf": 0.29,
        "avg_price_per_mwh": 35.0,
        "carbon_intensity_g_per_kwh": 360.0,
        "nearest_transmission_km": 8.1,
    },
    {
        "cell_id": "tx_003",
        "lat": 33.5779,
        "lon": -101.8552,
        "region": "Texas",
        "solar_cf": 0.29,
        "wind_cf": 0.36,
        "avg_price_per_mwh": 33.0,
        "carbon_intensity_g_per_kwh": 345.0,
        "nearest_transmission_km": 6.0,
    },
    {
        "cell_id": "midwest_001",
        "lat": 41.8781,
        "lon": -87.6298,
        "region": "Midwest",
        "solar_cf": 0.2,
        "wind_cf": 0.32,
        "avg_price_per_mwh": 46.0,
        "carbon_intensity_g_per_kwh": 520.0,
        "nearest_transmission_km": 11.4,
    },
    {
        "cell_id": "midwest_002",
        "lat": 44.9778,
        "lon": -93.265,
        "region": "Midwest",
        "solar_cf": 0.19,
        "wind_cf": 0.34,
        "avg_price_per_mwh": 43.0,
        "carbon_intensity_g_per_kwh": 470.0,
        "nearest_transmission_km": 9.0,
    },
    {
        "cell_id": "midwest_003",
        "lat": 39.7684,
        "lon": -86.1581,
        "region": "Midwest",
        "solar_cf": 0.21,
        "wind_cf": 0.28,
        "avg_price_per_mwh": 44.0,
        "carbon_intensity_g_per_kwh": 490.0,
        "nearest_transmission_km": 8.6,
    },
    {
        "cell_id": "gulf_001",
        "lat": 29.7604,
        "lon": -95.3698,
        "region": "Gulf Coast",
        "solar_cf": 0.24,
        "wind_cf": 0.28,
        "avg_price_per_mwh": 38.0,
        "carbon_intensity_g_per_kwh": 350.0,
        "nearest_transmission_km": 6.4,
    },
    {
        "cell_id": "gulf_002",
        "lat": 30.4515,
        "lon": -91.1871,
        "region": "Gulf Coast",
        "solar_cf": 0.23,
        "wind_cf": 0.25,
        "avg_price_per_mwh": 40.0,
        "carbon_intensity_g_per_kwh": 370.0,
        "nearest_transmission_km": 7.3,
    },
    {
        "cell_id": "gulf_003",
        "lat": 30.3322,
        "lon": -81.6557,
        "region": "Gulf Coast",
        "solar_cf": 0.22,
        "wind_cf": 0.2,
        "avg_price_per_mwh": 45.0,
        "carbon_intensity_g_per_kwh": 310.0,
        "nearest_transmission_km": 9.9,
    },
    {
        "cell_id": "southeast_001",
        "lat": 33.749,
        "lon": -84.388,
        "region": "Southeast",
        "solar_cf": 0.23,
        "wind_cf": 0.21,
        "avg_price_per_mwh": 49.0,
        "carbon_intensity_g_per_kwh": 340.0,
        "nearest_transmission_km": 10.8,
    },
    {
        "cell_id": "southeast_002",
        "lat": 35.2271,
        "lon": -80.8431,
        "region": "Southeast",
        "solar_cf": 0.22,
        "wind_cf": 0.19,
        "avg_price_per_mwh": 47.0,
        "carbon_intensity_g_per_kwh": 320.0,
        "nearest_transmission_km": 12.1,
    },
    {
        "cell_id": "southeast_003",
        "lat": 36.1627,
        "lon": -86.7816,
        "region": "Southeast",
        "solar_cf": 0.21,
        "wind_cf": 0.2,
        "avg_price_per_mwh": 43.0,
        "carbon_intensity_g_per_kwh": 410.0,
        "nearest_transmission_km": 7.8,
    },
    {
        "cell_id": "northeast_001",
        "lat": 42.3601,
        "lon": -71.0589,
        "region": "Northeast",
        "solar_cf": 0.17,
        "wind_cf": 0.24,
        "avg_price_per_mwh": 71.0,
        "carbon_intensity_g_per_kwh": 240.0,
        "nearest_transmission_km": 13.5,
    },
    {
        "cell_id": "northeast_002",
        "lat": 40.7128,
        "lon": -74.006,
        "region": "Northeast",
        "solar_cf": 0.16,
        "wind_cf": 0.2,
        "avg_price_per_mwh": 76.0,
        "carbon_intensity_g_per_kwh": 260.0,
        "nearest_transmission_km": 14.2,
    },
    {
        "cell_id": "northeast_003",
        "lat": 39.9526,
        "lon": -75.1652,
        "region": "Northeast",
        "solar_cf": 0.18,
        "wind_cf": 0.21,
        "avg_price_per_mwh": 63.0,
        "carbon_intensity_g_per_kwh": 300.0,
        "nearest_transmission_km": 10.7,
    },
    {
        "cell_id": "appalachia_001",
        "lat": 38.3498,
        "lon": -81.6326,
        "region": "Appalachia",
        "solar_cf": 0.19,
        "wind_cf": 0.23,
        "avg_price_per_mwh": 45.0,
        "carbon_intensity_g_per_kwh": 610.0,
        "nearest_transmission_km": 9.7,
    },
    {
        "cell_id": "appalachia_002",
        "lat": 37.5407,
        "lon": -77.436,
        "region": "Appalachia",
        "solar_cf": 0.2,
        "wind_cf": 0.22,
        "avg_price_per_mwh": 50.0,
        "carbon_intensity_g_per_kwh": 400.0,
        "nearest_transmission_km": 10.6,
    },
]


def build_fixture_dataframe() -> pd.DataFrame:
    frame = pd.DataFrame(ROWS)
    return frame.astype(COLUMN_DTYPES)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    build_fixture_dataframe().to_parquet(OUTPUT_PATH, index=False)
    print(f"Wrote {len(ROWS)} rows to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
